name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # This runs the action daily at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/KelvinTegelaar/CIPP-API.git
          git fetch upstream
          git checkout main

      - name: Merge changes from upstream
        run: |
          git merge upstream/main || true

      - name: Check if there are changes to push
        id: changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            echo "::set-output name=changes::false"
          else
            echo "Changes detected"
            echo "::set-output name=changes::true"
          fi

      - name: Push changes
        if: steps.changes.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git push origin main

      - name: Display Git config
        run: |
          git config --list

      - name: Debug Git status
        run: |
          git status
          git log -1
